### ISSUE TITLE
Colaboração

### ISSUE THREAD

**Issue by HClausing** [lucasteles/BrazilModels#8]
Olá.

Inicialmente gostaria de parabenizá-lo por esta bela iniciativa.

Gostaria de saber se está aceitando colaborações da comunidade para o projeto, não encontrei nada na documentação sobre, de forma que optei por abrir a issue,

**Comment by lucasteles** [comment]
Olá, 

Muito obrigado,

Boa, preciso color no readme um seção pra contribuição, mas em suma aceito sim. Caso seja alguma mudança de api ou feature só peço pra adicionar uma issue pra discutir antes

**Comment by HClausing** [comment]
Perfeito, assim farei.

Obrigado!
